server:
  name: opspaas
  host: "0.0.0.0"
  port: 10000

logger:
  path: /Users/dongxiaoqiang/go-project/opspaas/opspaas.log
  name: opspaas.log
  debug: true

mysql:
  host: 127.0.0.1
  user: root
  passwd: admin123
  db: opspaas
  Port: 3306

